services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - runner_data:/runner
      - runner_data:/actions-runner
    env_file:
      - .env
    restart: unless-stopped
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    environment:
      - GITHUB_TOKEN
      - GITHUB_URL
      - RUNNER_NAME
      - RUNNER_LABELS
      - RUNNER_WORKDIR
      - RUNNER_VERSION=2.328.0

volumes:
  runner_data: