services:

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    volumes:
      - ../src/DotNetApp.Server:/src/DotNetApp.Server
    environment:
      - WORKDIR=/src/DotNetApp.Server
    ports:
      - "5000:8080"
    networks:
      - default-network

  client:
    build:
      context: ..
      dockerfile: docker/Dockerfile.client
    volumes:
      - ../src/DotNetApp.Client:/src/DotNetApp.Client
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - default-network
    environment:
      - FRONTEND_API_BASE=http://api:8080/
  api-integration-tests:
    build:
      context: ..
      dockerfile: docker/Dockerfile.tests.api-integration
    depends_on:
      - api
    volumes:
      - ../src/DotNetApp.Server:/src/DotNetApp.Server
      - ../src/DotNetApp.Client:/src/DotNetApp.Client
      - ../tests/DotNetApp.Server.Tests.Integration:/src/DotNetApp.Server.Tests.Integration
      - nuget-packages:/root/.nuget/packages
    environment:
      - WORKDIR=/src/DotNetApp.Server.Tests.Integration
      - FRONTEND_API_BASE=http://api:8080/
      - NUGET_HTTP_TIMEOUT=200000
    networks:
      - default-network

  client-integration-tests:
    build:
      context: ..
      dockerfile: docker/Dockerfile.tests.client-integration
    depends_on:
      - client
    volumes:
      - ../src/DotNetApp.Client:/src/DotNetApp.Client
      - ../tests/DotNetApp.Client.Tests.Integration:/src/DotNetApp.Client.Tests.Integration
      - nuget-packages:/root/.nuget/packages
    environment:
      - WORKDIR=/src/DotNetApp.Client.Tests.Integration
      - FRONTEND_API_BASE=http://api:8080/
      - NUGET_HTTP_TIMEOUT=200000
    networks:
      - default-network

  e2e-tests:
    build:
      context: ..
      dockerfile: docker/Dockerfile.tests.e2e
    depends_on:
      - api
      - client
    environment:
      - WORKDIR=/src/DotNetApp.Tests.E2E
      - FRONTEND_API_BASE=http://api:8080/
      - FRONTEND_URL=http://client:80
      - NUGET_HTTP_TIMEOUT=200000
    networks:
      - default-network

networks:
  default-network:
    driver: bridge

volumes:
  nuget-packages:
    driver: local
