name: Chess — UI Tests

on:
  workflow_dispatch: {}

jobs:
  test:
    name: Run Chess UI tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore tests/Examples.Chess.UI/Examples.Chess.UI.csproj

      - name: Build
        run: dotnet build tests/Examples.Chess.UI/Examples.Chess.UI.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test tests/Examples.Chess.UI/Examples.Chess.UI.csproj --configuration Release --no-build --logger "trx" --verbosity normal
