name: CI Non-E2E

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  non-e2e-tests:
    name: non-e2e-tests
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
          key: nuget-cache-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-cache-${{ runner.os }}-

      - name: Cache dotnet install directory
        uses: actions/cache@v4
        with:
          path: |
            $HOME/.dotnet
          key: dotnet-cache-${{ runner.os }}-8.0-${{ hashFiles('global.json') }}
          restore-keys: |
            dotnet-cache-${{ runner.os }}-8.0-

      - name: Install dotnet locally (robust, try IPv4 then fallback)
        shell: bash
        run: |
          set -euo pipefail
          DOTNET_DIR="$HOME/.dotnet"
          echo "Installing dotnet locally to $DOTNET_DIR (try IPv4 then fallback)"
          mkdir -p "$DOTNET_DIR"
          if curl --ipv4 --retry 5 -fsSLo dotnet-install.sh https://dot.net/v1/dotnet-install.sh; then
            echo "Downloaded installer via IPv4"
            bash dotnet-install.sh --channel 8.0 --install-dir "$DOTNET_DIR" --no-path || true
          else
            echo "IPv4 download failed, trying normal download"
            curl --retry 5 -fsSLo dotnet-install.sh https://dot.net/v1/dotnet-install.sh
            bash dotnet-install.sh --channel 8.0 --install-dir "$DOTNET_DIR" --no-path || true
          fi
          echo "DOTNET_ROOT=$DOTNET_DIR" >> "$GITHUB_ENV"
          echo "$DOTNET_DIR" >> "$GITHUB_PATH"

      - name: Verify dotnet
        shell: bash
        run: |
          echo "--- dotnet --info ---"
          dotnet --info || true

      - name: Warm up NuGet cache (dotnet restore)
        shell: bash
        run: |
          echo "Warming NuGet cache with dotnet restore"
          dotnet restore DotNetApp.sln --verbosity minimal || true

      - name: Run non-E2E tests
        shell: bash
        run: |
          dotnet test DotNetApp.sln --verbosity minimal --filter "Category!=E2E"
