name: Coverage Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  collect-coverage:
    name: Run tests, collect coverage, and upload report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore DotNetApp.sln

      - name: Build project
        run: dotnet build DotNetApp.sln --configuration Release --no-restore

      - name: Run tests and generate Cobertura coverage
        run: |
          dotnet test DotNetApp.sln \
            --configuration Release \
            --no-build \
            --verbosity normal \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=cobertura \
            /p:CoverletOutput=./TestResults/Coverage/
        continue-on-error: false

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: TestResults/Coverage/
          retention-days: 7

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./TestResults/Coverage/coverage.cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }} # Required for private repos
          flags: unittests
          fail_ci_if_error: true
          verbose: true
