name: Deploy

on:
  workflow_run:
    workflows: ["Run Integration Tests (Docker Compose)"]
    types:
      - completed
  workflow_dispatch: {}

jobs:
  build-and-push:
    name: Build, publish and push images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore DotNetApp.sln

      - name: Publish client
        run: |
          dotnet publish src/DotNetApp.Client/DotNetApp.Client.csproj -c Release -o ./publish/client

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      - name: Build and push multi-arch Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.REGISTRY_HOST }}/${{ secrets.REGISTRY_NAMESPACE }}/dotnetapp-client:latest
            ${{ secrets.REGISTRY_HOST }}/${{ secrets.REGISTRY_NAMESPACE }}/dotnetapp-client:${{ github.sha }}
          file: docker/Dockerfile.client

      - name: Build and push API image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.api
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.REGISTRY_HOST }}/${{ secrets.REGISTRY_NAMESPACE }}/dotnetapp-api:latest
            ${{ secrets.REGISTRY_HOST }}/${{ secrets.REGISTRY_NAMESPACE }}/dotnetapp-api:${{ github.sha }}

  deploy:
    name: Deploy to environment
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: build-and-push
    environment:
      name: production
      url: https://example.com
    steps:
      - name: Notify deploy start
        run: echo "Deploying application - replace this step with real deploy commands"
