name: Test and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  DOTNET_VERSION: 8.0.x

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests with coverage
        run: |
          dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Aggregate coverage summary
        run: pwsh -NoProfile -ExecutionPolicy Bypass -File ./scripts/aggregate_coverage.ps1

      - name: Generate enhanced HTML coverage report
        run: pwsh -NoProfile -NonInteractive -ExecutionPolicy Bypass -File ./scripts/generate_coverage_html.ps1

      - name: Generate SVG coverage summary
        run: pwsh -NoProfile -NonInteractive -ExecutionPolicy Bypass -File ./scripts/generate_coverage_svg.ps1

      - name: Upload coverage report as Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./coverage-report

  deploy:
    needs: test-and-report
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
